jwt.secret= mySecretKey123456
jwt.expiration= 3600000

#default
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Logging
logging.level.root=INFO

# Actuator
management.endpoints.web.exposure.include=*

# Feign defaults
#spring.cloud.openfeign.client.config.default.connectTimeout=5000
#spring.cloud.openfeign.client.config.default.readTimeout=5000

# Banner
spring.main.banner-mode=off
